package schedulepg

import (
	"bytes"
	"context"
	"errors"
	"image"
	"image/png"
	"os"
	"reflect"
	"strings"
	"sync"
	"testing"

	"messeances/api/internal/cinemaimage"
)

func TestTheaterImagesPublicationIntegration(t *testing.T) {
	pool := newHistoryPool(t)
	ctx := t.Context()
	scheduleStore := NewStore(pool)
	data := testDataset()
	historyPublish(t, scheduleStore, data)
	path := t.TempDir()
	if e := os.Chmod(path, 0700); e != nil {
		t.Fatal(e)
	}
	media, e := cinemaimage.Open(path)
	if e != nil {
		t.Fatal(e)
	}
	t.Cleanup(func() {
		if media != nil {
			if e := media.Close(); e != nil {
				t.Error(e)
			}
		}
	})
	repo := cinemaimage.NewPostgresRepository(pool)
	service := cinemaimage.NewService(repo, media, nil, nil)
	id := cinemaimage.Identity{Provider: "ugc", ProviderTheaterID: "25"}
	var source bytes.Buffer
	if e := png.Encode(&source, image.NewNRGBA(image.Rect(0, 0, 32, 16))); e != nil {
		t.Fatal(e)
	}
	upload := func(revision int64) (cinemaimage.Result, error) {
		return service.Upload(ctx, id, func() (int64, []byte, string, error) { return revision, source.Bytes(), "image/png", nil })
	}
	if out, e := service.Remove(ctx, id, 0); e != nil || out.ImageRevision != 0 {
		t.Fatal(e)
	}
	historyCount(t, pool, "SELECT count(*) FROM theater_images", 0)
	first, e := upload(0)
	if e != nil || first.ImageRevision != 1 || first.Image == nil {
		t.Fatal("upload", e)
	}
	record, e := repo.Current(ctx, id)
	if e != nil {
		t.Fatal(e)
	}
	stored, e := service.Read(ctx, id, 1)
	if e != nil {
		t.Fatal(e)
	}
	// Persisted metadata and generated bytes survive a media-root reopen.
	if media.Close() != nil {
		t.Fatal("close")
	}
	media = nil
	media, e = cinemaimage.Open(path)
	if e != nil {
		t.Fatal(e)
	}
	service = cinemaimage.NewService(repo, media, nil, nil)
	if b, e := service.Read(ctx, id, 1); e != nil || !bytes.Equal(b, stored) {
		t.Fatal("restart persistence", e)
	}
	// Rebuild schedule names, addresses and generation, retaining cinema identity.
	data.Theaters[0].Name = "Renamed Cinema"
	data.Theaters[0].Address = "New Address"
	data.Theaters[1].Name = `UGC 100%_\ Cinema`
	data.Theaters[2].City = `Literal%_\Town`
	historyPublish(t, scheduleStore, data)
	// Both application and schema require slug == ID == provider + provider ID.
	// Keep that invariant rather than mutating the public schema for this fixture.
	if got, e := repo.Current(ctx, id); e != nil || got != record {
		t.Fatal("publication changed photo", e)
	}
	list, e := service.List(ctx, cinemaimage.ListQuery{Limit: 100})
	if e != nil || list.Total != 3 {
		t.Fatal(e)
	}
	found := false
	for _, cinema := range list.Items {
		if cinema.ProviderTheaterID == "25" {
			found = true
			if cinema.Name != "Renamed Cinema" || cinema.Slug != "ugc-25" || cinema.Address != "New Address" || cinema.ImageRevision != 1 || cinema.Image == nil {
				t.Fatalf("inventory %+v", cinema)
			}
		}
	}
	if !found {
		t.Fatal("missing inventory cinema")
	}
	// Cinema without showtimes still appears; a temporarily missing identity hides, not deletes, media.
	missing := data
	missing.Theaters = append([]TheaterRecord(nil), data.Theaters[1:]...)
	missing.Showtimes = nil
	historyPublish(t, scheduleStore, missing)
	list, e = service.List(ctx, cinemaimage.ListQuery{Limit: 100})
	if e != nil || list.Total != 2 {
		t.Fatal("showtime filter or absent identity", e)
	}
	if _, e = repo.Current(ctx, id); !errors.Is(e, cinemaimage.ErrNotFound) {
		t.Fatal(e)
	}
	if _, e = media.Read(ctx, record.Key, record.Width, record.Height, record.Size); e != nil {
		t.Fatal("absent cinema lost bytes", e)
	}
	historyPublish(t, scheduleStore, data)
	if got, e := repo.Current(ctx, id); e != nil || got != record {
		t.Fatal("reappearance lost association", e)
	}
	// First concurrent writes serialize in DB, independent of HTTP processing admission.
	other := cinemaimage.Identity{Provider: "ugc", ProviderTheaterID: "26"}
	next := record
	next.Key = strings.Repeat("b", 32) + ".webp"
	next.Revision = 0
	var wg sync.WaitGroup
	results := make(chan error, 2)
	for range 2 {
		wg.Add(1)
		go func() { defer wg.Done(); _, _, e := repo.Save(ctx, other, 0, next); results <- e }()
	}
	wg.Wait()
	close(results)
	success, conflict := 0, 0
	for e := range results {
		if e == nil {
			success++
		} else if errors.Is(e, cinemaimage.ErrConflict) {
			conflict++
		} else {
			t.Fatal("concurrent initial mutation", e)
		}
	}
	if success != 1 || conflict != 1 {
		t.Fatal(success, conflict)
	}
	// Replace/remove race: exactly one mutation advances the expected revision.
	next.Key = strings.Repeat("c", 32) + ".webp"
	results = make(chan error, 2)
	wg.Add(2)
	go func() { defer wg.Done(); _, _, e := repo.Save(ctx, other, 1, next); results <- e }()
	go func() { defer wg.Done(); _, _, e := repo.Remove(ctx, other, 1); results <- e }()
	wg.Wait()
	close(results)
	success, conflict = 0, 0
	for e := range results {
		if e == nil {
			success++
		} else if errors.Is(e, cinemaimage.ErrConflict) {
			conflict++
		} else {
			t.Fatal(e)
		}
	}
	if success != 1 || conflict != 1 {
		t.Fatal(success, conflict)
	}
	if _, _, e = repo.Remove(ctx, other, 1); !errors.Is(e, cinemaimage.ErrConflict) {
		t.Fatal("stale removal", e)
	}
	// Another provider may reuse the provider cinema ID without taking this image.
	kinepolis := kinepolisTestDataset()
	kinepolis.Theaters[0].ProviderID = "25"
	kinepolis.Theaters[0].ID = "kinepolis-25"
	kinepolis.Theaters[0].Slug = "kinepolis-25"
	kinepolis.Showtimes[0].TheaterID = "kinepolis-25"
	kinepolis.Showtimes[0].BookingURL = "https://kinepolis.fr/direct-vista-redirect/VS1/0/25/0"
	historyPublish(t, scheduleStore, data, kinepolis)
	// Inventory filters apply to all current cinemas before pagination, including
	// cinemas without showtimes. Count and rows use the same literal predicates.
	for _, tc := range []struct {
		name  string
		query cinemaimage.ListQuery
		total int
		ids   []string
	}{
		{"all", cinemaimage.ListQuery{Limit: 100}, 4, []string{"kinepolis-25", "ugc-25", "ugc-26", "ugc-99"}},
		{"provider_only", cinemaimage.ListQuery{Limit: 100, Provider: "ugc"}, 3, []string{"ugc-25", "ugc-26", "ugc-99"}},
		{"other_provider", cinemaimage.ListQuery{Limit: 100, Provider: "kinepolis"}, 1, []string{"kinepolis-25"}},
		{"search_name_case", cinemaimage.ListQuery{Limit: 100, Search: "cInEmA"}, 2, []string{"ugc-25", "ugc-26"}},
		{"search_city_case", cinemaimage.ListQuery{Limit: 100, Search: "LiLlE"}, 1, []string{"ugc-25"}},
		{"combined", cinemaimage.ListQuery{Limit: 100, Search: "lOm", Provider: "kinepolis"}, 1, []string{"kinepolis-25"}},
		{"provider_no_match", cinemaimage.ListQuery{Limit: 100, Provider: "pathe"}, 0, []string{}},
		{"search_no_match", cinemaimage.ListQuery{Limit: 100, Search: "absent"}, 0, []string{}},
		{"combined_no_match", cinemaimage.ListQuery{Limit: 100, Search: "lomme", Provider: "ugc"}, 0, []string{}},
		{"first_filtered_page", cinemaimage.ListQuery{Limit: 1, Search: "cinema", Provider: "ugc"}, 2, []string{"ugc-25"}},
		{"second_filtered_page", cinemaimage.ListQuery{Limit: 1, Offset: 1, Search: "cinema", Provider: "ugc"}, 2, []string{"ugc-26"}},
		{"past_filtered_page", cinemaimage.ListQuery{Limit: 1, Offset: 2, Search: "cinema", Provider: "ugc"}, 2, []string{}},
		{"provider_filtered_page", cinemaimage.ListQuery{Limit: 1, Offset: 1, Provider: "ugc"}, 3, []string{"ugc-26"}},
		{"city_not_on_first_page", cinemaimage.ListQuery{Limit: 1, Search: "town"}, 1, []string{"ugc-99"}},
		{"literal_percent", cinemaimage.ListQuery{Limit: 100, Search: "%"}, 2, []string{"ugc-26", "ugc-99"}},
		{"literal_underscore", cinemaimage.ListQuery{Limit: 100, Search: "_"}, 2, []string{"ugc-26", "ugc-99"}},
		{"literal_backslash", cinemaimage.ListQuery{Limit: 100, Search: `\`}, 2, []string{"ugc-26", "ugc-99"}},
		{"literal_combined", cinemaimage.ListQuery{Limit: 100, Search: `%_\`}, 2, []string{"ugc-26", "ugc-99"}},
		{"literal_no_match", cinemaimage.ListQuery{Limit: 100, Search: "%%"}, 0, []string{}},
		{"bound_quote", cinemaimage.ListQuery{Limit: 100, Search: "' OR 1=1 --"}, 0, []string{}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			got, err := service.List(ctx, tc.query)
			ids := make([]string, 0, len(got.Items))
			for _, cinema := range got.Items {
				ids = append(ids, cinema.TheaterID)
			}
			if err != nil || got.Total != tc.total || got.Limit != tc.query.Limit || got.Offset != tc.query.Offset || !reflect.DeepEqual(ids, tc.ids) {
				t.Fatalf("inventory ids=%v total=%d query=%+v err=%v", ids, got.Total, tc.query, err)
			}
		})
	}
	if got, e := repo.Current(ctx, cinemaimage.Identity{Provider: "kinepolis", ProviderTheaterID: "25"}); e != nil || got.Revision != 0 || got.Key != "" {
		t.Fatal("provider identity collision", e)
	}
	if _, e = upload(0); !errors.Is(e, cinemaimage.ErrConflict) {
		t.Fatal(e)
	}
	removed, e := service.Remove(ctx, id, 1)
	if e != nil || removed.ImageRevision != 2 || removed.Image != nil {
		t.Fatal(e)
	}
	if got, e := repo.Current(ctx, id); e != nil || got.Revision != 2 || got.Key != "" {
		t.Fatal("tombstone reset", e)
	}
	if out, e := service.Remove(ctx, id, 2); e != nil || out.ImageRevision != 2 {
		t.Fatal("empty no-op", e)
	}
	if _, e = service.Read(ctx, id, 1); !errors.Is(e, cinemaimage.ErrImageNotFound) {
		t.Fatal(e)
	}
	if _, e = media.Read(ctx, record.Key, record.Width, record.Height, record.Size); !errors.Is(e, os.ErrNotExist) {
		t.Fatal("postcommit predecessor retained", e)
	}
	historyExec(t, pool, "UPDATE theater_images SET image_revision=9007199254740991 WHERE provider='ugc' AND provider_theater_id='25'")
	if _, e = upload(cinemaimage.MaxRevision); !errors.Is(e, cinemaimage.ErrStorage) {
		t.Fatal("exhausted revision mutated", e)
	}
	refs, e := repo.References(context.Background(), []string{next.Key})
	if e != nil || refs == nil {
		t.Fatal("media barrier references", e)
	}
}
